name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: wordpress
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer, phpcs, phpunit
          extensions: mysqli
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run PHPCS
        run: vendor/bin/phpcs --standard=phpcs.xml --ignore=vendor postsecret/wp-content
      - name: Run PHPUnit
        run: vendor/bin/phpunit
